logging:
    file:
        name: logs/greengarden.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /greengarden
spring:
    application:
        name: GreenGarden
        version: ${version}
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: rmflszjavbxj123!
        url: jdbc:oracle:thin:@43.203.164.115:1522:xe
        username: team3

    devtools:
        livereload:
            enabled: true
    jpa:
        autoconfigure:
            exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 30MB
